### PR TITLE
Makefile improvements

### PR DESCRIPTION
**Pull request by teknokatze**
small improvements to the makefile

### CODE REVIEW

**Comment by teknokatze** [comment]
Let's do this in small steps since you are moving to fast for me (see previous PR)

**Comment by teknokatze** [comment]
Too fast meaning: If you leave the Makefile untouched for a while I can send changes your way, or you pick and apply when I have it read again. What you wanted to achieve is incomplete but in the right direction.
In general assuming the location where luajit is installed as a hardcoded location isn't good practice regardless of the underlying OS, we should be able to set it as package maintainers without sed.

**Comment by n-ham** [comment]
Sorry I haven't gotten on to this yet, have been flat out working on some new version. I haven't forgotten and will try to get on to it soon. I am also working with the person who does the FreeBSD ports release so that's why there may be some more changes to the makefile as well..

**Comment by teknokatze** [comment]
Hi, no problem.
I have seen the patch in freebsd ports earlier this month and it doesn't look applicable to a package manager which targets more systems (it addressed very FreeBSD specific needs). Do you suggest that for now I'll patch this up locally and wait for the freebsd patch and a new release?
Would you be able to work with a patch without git when I'm done and you would just add the work to the release, or should I send a new patch rewriting the Makefile once you are done?

**Comment by n-ham** [comment]
Some of the stuff where $(MAKE) was put in has changed, but the Makefile has been updated to use $(MAKE).

I am not the biggest fan of .gitignore files, I find it easier to end up with files I don't want committed to the repo when I do that. I merged it so the changes were counted in the repo history but am going to remove it, happy for you to try to convince me to add it back again (would need to update it for other platforms too like Windows as well). 

What I do for development is copy my local clone of say nsm-gh to nsm-dev, do development in nsm-dev and then when I'm ready to commit/push the changes I use `git status` in nsm-dev to work out all the changes I've made and copy those files in to nsm-gh, nsm-gl, nsm-bb, nsm-snap, nsm-flatpak etc. to be commited and pushed (I copy paste the add/commit/push/tag/etc. commands so I'm not typing them out a heap of times for all the different mirrors).

**Comment by teknokatze** [comment]
Okay, thanks.

One criticism with the earlier version of this Makefile from us was that compilers are assumed. FreeBSD can have a configuration where clang does not do the builds (pkgsrc, with clang OR gcc), best to use the values set by make.

I'll see that I work in the rest of my original patch.

**Comment by n-ham** [comment]
I just updated changes to the Makefile and Lua.h so that it can compile with any recent version of Lua or LuaJIT. Hopefully all the $(MAKE) stuff is now sorted as well. `$(MAKE) clean` should work on Windows once the beta version has been updated with the dev version as Mike Pall closed the issue I made about it the other day saying it's been fixed..

**Comment by n-ham** [comment]
I have also added https://nift.cc/docs/make.html to the website which is linked from the install from source sections of the linux/osx/windows install pages.

**Pull request merged**
